# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3hDzG1Y6n4-OM-S3KuLkElsWXATGcd_
"""

# ============================================================
#  PROJETO VISUALIZACAO DA INFORMACAO — 5 TÉCNICAS
#  Visualização da Informação
#  Dataset: precipitation.csv
#  Gilberto Gamarano
#  Ciência de dados
# ============================================================

# --- IMPORTACOES ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import networkx as nx
import requests

sns.set_theme()

# --- UPLOAD DO ARQUIVO ---
from google.colab import files
uploaded = files.upload()

df = pd.read_csv("precipitation.csv")

# --- TRATAMENTO DE DATA ---
df['data'] = pd.to_datetime(df['date'], format="%d/%m/%Y")
df.drop(columns=["date"], inplace=True)

# --- FILTRAR ESTADO ---
estado = "BA"       # você pode alterar para SE ou RR
df_est = df[df['state'] == estado].copy()

# ============================================================
#  1 — ESTATISTICA DESCRITIVA — GRAFICO DE BARRAS
# ============================================================
df_est["ano"] = df_est["data"].dt.year
chuva_anual = df_est.groupby("ano")["precipitation"].sum().reset_index()

fig = px.bar(
    chuva_anual,
    x="ano",
    y="precipitation",
    title=f"(1) Gráfico de Barras — Precipitação Anual — {estado}",
    labels={"precipitation": "Precipitação (mm)", "ano": "Ano"}
)
fig.show()

# ============================================================
#  2 — INFORMACAO TEMPORAL — GRAFICO DE LINHAS
# ============================================================
fig = px.line(
    df_est,
    x="data",
    y="precipitation",
    title=f"(2) Série Temporal — Precipitação — {estado}",
    labels={"data": "Data", "precipitation": "Precipitação (mm)"}
)
fig.show()

# ============================================================
#  3 — INFORMACAO GEOGRAFICA — MAPA CHOROPLETH
# ============================================================

# --- GEOJSON DOS ESTADOS DO BRASIL ---
url_geojson = "https://raw.githubusercontent.com/codeforamerica/click_that_hood/master/public/data/brazil-states.geojson"
geojson = requests.get(url_geojson).json()

# Média de precipitação por estado
media_estado = df.groupby("state")["precipitation"].mean().reset_index()

# Nome completo dos estados conforme o GeoJSON
mapa_estados = {
    "BA": "Bahia",
    "SE": "Sergipe",
    "RR": "Roraima"
}

media_estado["estado_nome"] = media_estado["state"].map(mapa_estados)

# --- CHOROPLETH ---
fig = px.choropleth(
    media_estado,
    geojson=geojson,
    locations="estado_nome",
    featureidkey="properties.name",
    color="precipitation",
    color_continuous_scale="Blues",
    title="(3) Mapa Choropleth — Precipitação Média por Estado",
    labels={"precipitation": "Precipitação Média (mm)", "estado_nome": "Estado"}
)
fig.update_geos(fitbounds="locations", visible=False)
fig.show()

# ============================================================
#  4 — INFORMACAO HIERARQUICA — SUNBURST
# ============================================================
meses_pt = {
    1: "Janeiro", 2: "Fevereiro", 3: "Março", 4: "Abril",
    5: "Maio", 6: "Junho", 7: "Julho", 8: "Agosto",
    9: "Setembro", 10: "Outubro", 11: "Novembro", 12: "Dezembro"
}

df_est["mes"] = df_est["data"].dt.month.map(meses_pt)

fig = px.sunburst(
    df_est,
    path=["state", "ano", "mes"],
    values="precipitation",
    title="(4) Gráfico Sunburst — Estado > Ano > Mês",
    labels={"precipitation": "Precipitação (mm)", "ano": "Ano", "mes": "Mês"}
)
fig.show()
# ============================================================
#  5 — REDES E GRAFOS — NODE-LINK
# ============================================================

# 1 — Soma anual
df_anual = df_est.groupby("ano")["precipitation"].sum().reset_index()

# 2 — Media da precipitacao anual
media_anual = df_anual["precipitation"].mean()

# 3 — Criar grafo
G = nx.Graph()

for _, row in df_anual.iterrows():
    ano = int(row["ano"])
    nivel = "Alta precipitação" if row["precipitation"] > media_anual else "Baixa precipitação"

    G.add_node(ano)
    G.add_node(nivel)
    G.add_edge(ano, nivel)

# 4 — Plot
plt.figure(figsize=(12,8))

pos = nx.spring_layout(G, k=0.8, seed=42)

cores = ["lightgreen" if isinstance(n, int) else "skyblue" for n in G.nodes()]

nx.draw(
    G,
    pos,
    with_labels=True,
    node_color=cores,
    node_size=1200,
    font_size=10,
    width=2
)

plt.title("(5) Grafo Node-Link — Ano x Nível de Precipitação")
plt.show()
